# Generated by Django 5.2.1 on 2026-02-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
