# Generated by Django 5.2.1 on 2026-02-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_order_user_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.TextField(blank=True, help_text="Search keywords and synonyms (e.g. 'donak, magiz' for apricot kernels)", null=True),
        ),
    ]
