# Generated by Django 5.2.1 on 2026-02-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_product_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='guest_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='guest_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
