# Generated by Django 5.2.1 on 2026-02-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_order_phone_number_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
